version: '3.8'

services:

  redis:
    image: redis:alpine 
    container_name: redis_container

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db_container

  app:
    image: django_image
    build: . 
    ports:
      - 8000:8000
    volumes:
      - .:/django 
    container_name: app_container
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  celery:
    restart: always 
    build: 
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - .:/django 
    container_name: celery
    depends_on:
      - db
      - redis
      - app 

    